queue_rules:
  - name: default
    queue_conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
      - status-success=Travis CI - Pull Request
      - label=ready-to-merge
      - label!=do-not-merge
    merge_conditions:
      - status-success=Travis CI - Pull Request
    merge_method: squash

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
