module.exports = {
    clearMocks: true,
    collectCoverage: false,
    collectCoverageFrom: [
        'src/**/*.js',
        '!src/utils/*.js',
        '!src/**/messages.js',
        '!src/**/__tests__/**',
        '!**/node_modules/**',
    ],
    coverageDirectory: '<rootDir>/reports',
    globals: {
        __NAME__: 'name',
        __VERSION__: 'version',
        __LANGUAGE__: 'en-US',
    },
    moduleNameMapper: {
        '\\.(css|scss|less|html)$': '<rootDir>/test-utils/styleMock.js',
        '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2)$': '<rootDir>/test-utils/fileMock.js',
        'box-annotations-locale-data': '<rootDir>/test-utils/i18nMock.js',
        'box-elements-messages': '<rootDir>/test-utils/i18nMock.js',
        'react-intl': '<rootDir>/test-utils/react-intl-mocks.js',
        'react-intl-locale-data': '<rootDir>/node_modules/react-intl/locale-data/en.js',
        intl: '<rootDir>/test-utils/lib-intl-mock.js',
        mousetrap: '<rootDir>/test-utils/moduleMock.js',
        rangy: '<rootDir>/test-utils/moduleMock.js',
    },
    restoreMocks: true,
    roots: ['src'],
    setupFiles: ['jest-canvas-mock'],
    setupFilesAfterEnv: ['<rootDir>/build/enzyme-adapter.js'],
    snapshotSerializers: ['enzyme-to-json/serializer'],
    transformIgnorePatterns: ['node_modules/(?!(box-ui-elements)/)'],
};
