module.exports = {
    clearMocks: true,
    collectCoverage: false,
    collectCoverageFrom: ['**/*.{ts,tsx}', '!**/*.d.ts', '!**/messages.{ts,tsx}', '!**/node_modules/**'],
    coverageDirectory: '<rootDir>/reports',
    globals: {
        __NAME__: 'name',
        __VERSION__: 'version',
        __LANGUAGE__: 'en-US',
    },
    moduleNameMapper: {
        '\\.(css|scss|less|html)$': '<rootDir>/scripts/jest/styleMock.js',
        '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2)$': '<rootDir>/scripts/jest/fileMock.js',
        '@popperjs/core': '<rootDir>/scripts/jest/popperMock.js',
        'box-annotations-locale-data': '<rootDir>/scripts/jest/i18nMock.js',
        'box-elements-messages': '<rootDir>/scripts/jest/i18nMock.js',
        'react-intl': '<rootDir>/scripts/jest/react-intl-mock.js',
        'react-intl-locale-data': '<rootDir>/node_modules/react-intl/locale-data/en.js',
        mousetrap: '<rootDir>/scripts/jest/moduleMock.js',
        rangy: '<rootDir>/scripts/jest/moduleMock.js',
    },
    restoreMocks: true,
    roots: ['src'],
    setupFiles: ['jest-canvas-mock'],
    setupFilesAfterEnv: ['<rootDir>/scripts/jest/enzyme-adapter.js'],
    snapshotSerializers: ['enzyme-to-json/serializer'],
    transformIgnorePatterns: ['node_modules/(?!(box-ui-elements)/)'],
};
