// flow-typed signature: 43dc66b0844a949dcb4c6a9fa77e8d9f
// flow-typed version: <<STUB>>/pikaday_v^1.7.0/flow_v0.79.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pikaday'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pikaday' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pikaday/pikaday' {
  declare module.exports: any;
}

declare module 'pikaday/plugins/pikaday.jquery' {
  declare module.exports: any;
}

declare module 'pikaday/tests/methods' {
  declare module.exports: any;
}

declare module 'pikaday/tests/module' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pikaday/pikaday.js' {
  declare module.exports: $Exports<'pikaday/pikaday'>;
}
declare module 'pikaday/plugins/pikaday.jquery.js' {
  declare module.exports: $Exports<'pikaday/plugins/pikaday.jquery'>;
}
declare module 'pikaday/tests/methods.js' {
  declare module.exports: $Exports<'pikaday/tests/methods'>;
}
declare module 'pikaday/tests/module.js' {
  declare module.exports: $Exports<'pikaday/tests/module'>;
}
