// flow-typed signature: 477c7f722a99d32f42a5f04c782746f5
// flow-typed version: <<STUB>>/react-process-string_v^1.2.0/flow_v0.79.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-process-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-process-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-process-string/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-process-string/dist/index.js' {
  declare module.exports: $Exports<'react-process-string/dist/index'>;
}
declare module 'react-process-string/index' {
  declare module.exports: $Exports<'react-process-string'>;
}
declare module 'react-process-string/index.js' {
  declare module.exports: $Exports<'react-process-string'>;
}
