// flow-typed signature: ef12d4a1d1a2d98acc89083c86b64481
// flow-typed version: <<STUB>>/scroll-into-view-if-needed_v^2.2.16/flow_v0.79.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scroll-into-view-if-needed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scroll-into-view-if-needed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scroll-into-view-if-needed/es/index' {
  declare module.exports: any;
}

declare module 'scroll-into-view-if-needed/es/types' {
  declare module.exports: any;
}

declare module 'scroll-into-view-if-needed/umd/scroll-into-view-if-needed' {
  declare module.exports: any;
}

declare module 'scroll-into-view-if-needed/umd/scroll-into-view-if-needed.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scroll-into-view-if-needed/es/index.js' {
  declare module.exports: $Exports<'scroll-into-view-if-needed/es/index'>;
}
declare module 'scroll-into-view-if-needed/es/types.js' {
  declare module.exports: $Exports<'scroll-into-view-if-needed/es/types'>;
}
declare module 'scroll-into-view-if-needed/index' {
  declare module.exports: $Exports<'scroll-into-view-if-needed'>;
}
declare module 'scroll-into-view-if-needed/index.js' {
  declare module.exports: $Exports<'scroll-into-view-if-needed'>;
}
declare module 'scroll-into-view-if-needed/umd/scroll-into-view-if-needed.js' {
  declare module.exports: $Exports<'scroll-into-view-if-needed/umd/scroll-into-view-if-needed'>;
}
declare module 'scroll-into-view-if-needed/umd/scroll-into-view-if-needed.min.js' {
  declare module.exports: $Exports<'scroll-into-view-if-needed/umd/scroll-into-view-if-needed.min'>;
}
